# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

batwing_rcpp <- function(data, reps, burnin, treebetN, Nbetsamp, mupriorsvec, nmuprior, Nprior, alphaprior, forensicmode, progress, trace) {
    .Call(`_rforensicbatwing_batwing_rcpp`, data, reps, burnin, treebetN, Nbetsamp, mupriorsvec, nmuprior, Nprior, alphaprior, forensicmode, progress, trace)
}

